name: "ONVIF Video Camera V1.4"
packageKey: "onvif_v1.4"
vendorName: "dMac"
description: "ONVIF Doorbell Edge Driver"
version: "4.0"
permissions:
  lan: {}
  discovery: {}
driver:
  main: "src/init.lua"  # Explicitly points to init.lua in hubpackage/src/
profiles:
  - "profiles/onvifcam_v4.yaml"  # Links your profile