name: "ONVIF Video Camera V2.1"
packageKey: "onvif_v2.1"
vendorName: "dMac"
description: "ONVIF Doorbell Edge Driver"
version: "4.0"
permissions:
  lan: {}
  discovery: {}
driver:
  main: "src/init.lua"  # Explicitly points to init.lua in hubpackage/src/
profiles:
  - "profiles/snapshot-tile-profile.yaml"  # Links your profile