presentationId: snapshot-tile-doorbell-config
manufacturerName: SmartThingsCommunity
type: profile
dashboard:
  states:
    - component: main
      capability: pianodream12480.onvifStatus
      version: 1
    - component: main
      capability: pianodream12480.doorbell
      version: 1
  actions:
    - component: main
      capability: refresh
      version: 1
    - component: main
      capability: pianodream12480.twoWayAudio
      version: 1
    - component: main
      capability: pianodream12480.customChimeControl
      version: 1
detailView:
  - component: main
    capability: videoStream
    version: 1
  - component: main
    capability: pianodream12480.doorbell
    version: 1
  - component: main
    capability: pianodream12480.twoWayAudio
    version: 1
  - component: main
    capability: pianodream12480.customChimeControl
    version: 1
  - component: main
    capability: pianodream12480.audioOutput
    version: 1
  - component: main
    capability: refresh
    version: 1
  - component: main
    capability: pianodream12480.onvifStatus
    version: 1
  - component: main
    capability: tamperAlert
    version: 1
automation:
  conditions:
    - component: main
      capability: pianodream12480.doorbell
      version: 1
    - component: main
      capability: tamperAlert
      version: 1
  actions:
    - component: main
      capability: pianodream12480.customChimeControl
      version: 1
    - component: main
      capability: pianodream12480.twoWayAudio
      version: 1
    - component: main
      capability: refresh
      version: 1
metadata:
  vid: baf61390-c4cb-3c88-b101-195b632c91ed
  mnmn: SmartThingsCommunity